# Generated by Django 2.0.4 on 2018-10-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=64)),
                ('mail', models.CharField(max_length=64)),
                ('age', models.CharField(max_length=64)),
            ],
        ),
    ]
