# Generated by Django 2.1.2 on 2018-11-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181113_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=64)),
                ('page_num', models.IntegerField(null=True)),
                ('author', models.ManyToManyField(to='blog.Author')),
            ],
        ),
    ]
