# Generated by Django 2.1.2 on 2018-11-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
